<font color='LightSkyBlue'>
<font size=6>
        
**Aprendiendo Pytorch**

<font color = 'MediumVioletRed'>
<font size = 5>
INSTALACIÓN

<font color = 'AntiqueWhite'>
<font size = 3>
Para instalar PyTorch en Manjaro, lo hacemos como se indica en la web oficial de <a href=https://pytorch.org//>PyTorch</a>. Teniendo en cuenta que ya estaba previamente instalado Anaconda.

In [45]:
# Verificamos la instalación
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.9990, 0.5822, 0.5947],
        [0.0278, 0.5292, 0.4575],
        [0.4482, 0.4245, 0.3507],
        [0.4277, 0.9356, 0.8514],
        [0.6041, 0.8712, 0.7136]])


In [46]:
# Verificamos if GPU is enable and accessible by PyTorch
torch.cuda.is_available()

True

In [47]:
# Se listan los paquetes instalados en el entorno virtual
!pip list

Package                   Version
------------------------- --------------
anyio                     4.6.2.post1
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     24.2.0
babel                     2.16.0
beautifulsoup4            4.12.3
bleach                    6.2.0
Brotli                    1.0.9
certifi                   2024.8.30
cffi                      1.17.1
charset-normalizer        3.3.2
comm                      0.2.2
contourpy                 1.3.0
cycler                    0.12.1
debugpy                   1.8.8
decorator                 5.1.1
defusedxml                0.7.1
exceptiongroup            1.2.2
executing                 2.1.0
fastjsonschema            2.20.0
filelock                  3.13.1
fonttools                 4.54.1
fqdn                      1.5.1
gmpy2                     2.1.2
h11                       0.14.0
httpcore

<font color = 'Chartreuse'>
<font size = 5>
TENSORES

<font color = 'AntiqueWhite'>
<font size = 3>
    
- Un torch.Tensor es una matriz multi-dimensional que contiene elementos de un solo tipo de dato.
    
- Por default data type of float32.

In [48]:
import numpy as np

<font color = 'Tomato'>
<font size = 5>
LISTAS

In [49]:
# Multi-dimentional array
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

<font color = 'MediumSpringGreen'>
<font size = 5>
NUMPY ARRAYS

In [50]:
# 3 Rows and 4 Columns
np1 = np.random.rand(3,4)
np1

array([[0.21715081, 0.85155792, 0.20453059, 0.37448949],
       [0.64291711, 0.37149902, 0.83386698, 0.4953125 ],
       [0.44166718, 0.4411257 , 0.92747274, 0.38141533]])

In [51]:
# Verificamos el data type
np1.dtype

dtype('float64')

In [52]:
# Creando tensores de 2D, 2 capas, 3 rows and 4 columns
tensor_2d = torch.rand(3,4) # torch.rand() crea un tensor de números aleatorios entre 0 y 1
tensor_2d

tensor([[0.4714, 0.9037, 0.8147, 0.1893],
        [0.4185, 0.4540, 0.9417, 0.3364],
        [0.0097, 0.5982, 0.7791, 0.1222]])

In [53]:
# Creando tensores de 3D, 3 rows and 4 columns
tensor_3d = torch.zeros(2,3,4) 
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [54]:
# Verificamos el data type
print(tensor_2d.dtype)
print(tensor_3d.dtype)

torch.float32
torch.float32


In [55]:
# Create tensor out numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2172, 0.8516, 0.2045, 0.3745],
        [0.6429, 0.3715, 0.8339, 0.4953],
        [0.4417, 0.4411, 0.9275, 0.3814]], dtype=torch.float64)

In [56]:
# Verificamos el data type
my_tensor.dtype

torch.float64

<font color = 'CornflowerBlue'>
<font size = 5>
TENSOR OPERATIONS

In [57]:
my_torch = torch.arange(10) # crea un tensor 1D con una sucesión de números del 1 al 9
print(my_torch)
print(my_torch.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


In [58]:
# Reshape and View
my_torch = my_torch.reshape(2,5) # this method change the shape of a tensor without changing its data
my_torch # the new shape of 2 rows and 5 columns

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [59]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [61]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

<font color = 'MediumSlateBlue'>
<font size = 3>
Differences between shape and view in PyTorch, <a href=https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch/>Click here</a>.

In [63]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [65]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [66]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

<font color = 'Chocolate'>
<font size = 3>
Slices allow you to grab a section of your tensor.

In [67]:
my_torch7 = torch.arange(10) # crea un tensor unidimensional que contiene los numeros del 0 al 9. 
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
# Grab a specific item
my_torch7[7] # accede al elemento de la posicion 7 del tensor

tensor(7)

In [69]:
print(my_torch7[7])

tensor(7)


In [70]:
print(my_torch7)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [71]:
# Grab slice
my_torch8 = my_torch7.reshape(5,2) # cambia la forma del tensor a una matriz de 5 filas y 2 columnas, se reorganiza
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [72]:
my_torch8[:,1] # extrae todos los elementos de la columna 1

tensor([1, 3, 5, 7, 9])

In [73]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

<font color = 'DeepSkyBlue'>
<font size = 4>
TENSOR MATH OPERATIONS
    
- Add, Subtract, Multiply, Divide, Remainders, Exponents.
- Shorthand and uh, Longhand.
- Reassignament

In [74]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [75]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [76]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [77]:
# Subtraction 
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [78]:
# Sub Function 
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [79]:
# Miltiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [80]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [81]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [82]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [83]:
# Reminder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [84]:
# Reminder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [85]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [86]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [87]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])